version: '3'
services:
  auth-db:
    image: registry.gitlab.com/dalibo/postgresql_anonymizer
    container_name: auth-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    command: postgres -c shared_preload_libraries='anon'
    env_file:
      - ./.env
    ports:
      - '${DATABASE_HOST}:${POSTGRES_PORT}:5432'
    networks:
      - network_users

  auth-api:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: auth-api
    command: sh -c 'npm run build && npm run dev'
    environment:
      DB_TYPE: ${PGDB_TYPE}
      DB_HOST: ${PGHOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      API_SECRET: ${API_SECRET}
      DB_ENTITIES: ${DB_ENTITIES}
      DB_MIGRATIONS: ${DB_MIGRATIONS}
    ports:
      - '${ENV_SERVER_PORT}:${ENV_SERVER_PORT}'
    volumes:
      - ../../:/auth-api
      - /auth-api/node_modules
    tty: true
    networks:
      - network_users
    restart: 'always'
    env_file:
      - ./.env

networks:
  network_users:
    name: network_users
