version: '3'
services:
  auth-db:
    image: postgres:alpine
    container_name: auth-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    env_file:
      - ./.env
    ports:
      - '${DATABASE_HOST}:${POSTGRES_PORT}:5432'
    networks:
      - network_users

  auth-api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      DB_TYPE: ${PGDB_TYPE}
      DB_HOST: ${PGHOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_ENTITIES: ${DB_ENTITIES}
      DB_MIGRATIONS: ${DB_MIGRATIONS}
    ports:
      - '${ENV_SERVER_PORT}:${ENV_SERVER_PORT}'
    networks:
      - network_users
    restart: 'always'
    env_file:
      - ./.env

networks:
  network_users:
    name: network_users
