server:
  port: 8081

spring: 
  application:
    name: product-api 

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
    format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  sql:
    init:
      platform: postgresql
      continue-on-error: true