INSERT INTO CATEGORY (ID, DESCRIPTION) values(1000, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) values(1001, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) values(1002, 'Books');


INSERT INTO SUPPLIER (ID, NAME) values(1000, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) values(1001, 'Amazon');


INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) values(1000, 'Crise nas Infinitas Terras',1000,1000,10);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) values(1001, 'Interstelar',1001,1001,5);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) values(1002, 'Hary Potter e a pedra Filosofal',1001,1002,20);
